/*
 * Class auto generated by TexturePacker
 *
 * Contains references to each image within the sprite sheet.
 *
 * https://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:33079f755fb94444f2aaf68f025b8c2c:c82bf352092f05f5b6202c1661bbfac4:d39126f90387280a1fa5d6da0c385cf4$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class 
	{
		public const string Survivor-strafe_right_0 = "survivor-strafe_right_0";
		public const string Survivor-strafe_right_1 = "survivor-strafe_right_1";
		public const string Survivor-strafe_right_2 = "survivor-strafe_right_2";
		public const string Survivor-strafe_right_3 = "survivor-strafe_right_3";
		public const string Survivor-strafe_right_4 = "survivor-strafe_right_4";
		public const string Survivor-strafe_right_5 = "survivor-strafe_right_5";
		public const string Survivor-strafe_right_6 = "survivor-strafe_right_6";
		public const string Survivor-strafe_right_7 = "survivor-strafe_right_7";
		public const string Survivor-strafe_right_8 = "survivor-strafe_right_8";
		public const string Survivor-strafe_right_9 = "survivor-strafe_right_9";
		public const string Survivor-strafe_right_10 = "survivor-strafe_right_10";
		public const string Survivor-strafe_right_11 = "survivor-strafe_right_11";
		public const string Survivor-strafe_right_12 = "survivor-strafe_right_12";
		public const string Survivor-strafe_right_13 = "survivor-strafe_right_13";
		public const string Survivor-strafe_right_14 = "survivor-strafe_right_14";
		public const string Survivor-strafe_right_15 = "survivor-strafe_right_15";
		public const string Survivor-strafe_right_16 = "survivor-strafe_right_16";
		public const string Survivor-strafe_right_17 = "survivor-strafe_right_17";
		public const string Survivor-strafe_right_18 = "survivor-strafe_right_18";
		public const string Survivor-strafe_right_19 = "survivor-strafe_right_19";
	}
}