/*
 * Class auto generated by TexturePacker
 *
 * Contains references to each image within the sprite sheet.
 *
 * https://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:a9ee897770fe037a95974d36f2fa33fe:3d27d11f2d7b9ac7898fa675c9a2700b:0d9e4ed205702348fdb36f164327995c$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class 
	{
		public const string Survivor-strafe_left_0 = "survivor-strafe_left_0";
		public const string Survivor-strafe_left_1 = "survivor-strafe_left_1";
		public const string Survivor-strafe_left_2 = "survivor-strafe_left_2";
		public const string Survivor-strafe_left_3 = "survivor-strafe_left_3";
		public const string Survivor-strafe_left_4 = "survivor-strafe_left_4";
		public const string Survivor-strafe_left_5 = "survivor-strafe_left_5";
		public const string Survivor-strafe_left_6 = "survivor-strafe_left_6";
		public const string Survivor-strafe_left_7 = "survivor-strafe_left_7";
		public const string Survivor-strafe_left_8 = "survivor-strafe_left_8";
		public const string Survivor-strafe_left_9 = "survivor-strafe_left_9";
		public const string Survivor-strafe_left_10 = "survivor-strafe_left_10";
		public const string Survivor-strafe_left_11 = "survivor-strafe_left_11";
		public const string Survivor-strafe_left_12 = "survivor-strafe_left_12";
		public const string Survivor-strafe_left_13 = "survivor-strafe_left_13";
		public const string Survivor-strafe_left_14 = "survivor-strafe_left_14";
		public const string Survivor-strafe_left_15 = "survivor-strafe_left_15";
		public const string Survivor-strafe_left_16 = "survivor-strafe_left_16";
		public const string Survivor-strafe_left_17 = "survivor-strafe_left_17";
		public const string Survivor-strafe_left_18 = "survivor-strafe_left_18";
		public const string Survivor-strafe_left_19 = "survivor-strafe_left_19";
	}
}