/*
 * Class auto generated by TexturePacker
 *
 * Contains references to each image within the sprite sheet.
 *
 * https://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:736a2a04e999254fd0b7ef132c0b0743:dc148031c0fa9ca5cbebb7f66f9b9148:9af7c318705ee46374108dd4f0f96851$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class survivor-run
	{
		public const string Survivor-run_2 = "survivor-run_2";
		public const string Survivor-run_3 = "survivor-run_3";
		public const string Survivor-run_4 = "survivor-run_4";
		public const string Survivor-run_5 = "survivor-run_5";
		public const string Survivor-run_6 = "survivor-run_6";
		public const string Survivor-run_7 = "survivor-run_7";
		public const string Survivor-run_8 = "survivor-run_8";
		public const string Survivor-run_9 = "survivor-run_9";
		public const string Survivor-run_12 = "survivor-run_12";
		public const string Survivor-run_13 = "survivor-run_13";
		public const string Survivor-run_14 = "survivor-run_14";
		public const string Survivor-run_15 = "survivor-run_15";
		public const string Survivor-run_16 = "survivor-run_16";
		public const string Survivor-run_17 = "survivor-run_17";
		public const string Survivor-run_18 = "survivor-run_18";
		public const string Survivor-run_19 = "survivor-run_19";
	}
}